// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolAPI.Models;

#nullable disable

namespace SchoolAPI.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolAPI.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Sections")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Ali Mouelhi",
                            Name = "ENISo",
                            Rating = 3.5,
                            Sections = "IA, GTE, GMP",
                            WebSite = "http://www.eniso.rnu.tn"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Sana Khemiri",
                            Name = "ENIM",
                            Rating = 4.2000000000000002,
                            Sections = "Mécanique, Électrique, Énergétique",
                            WebSite = "http://www.enim.rnu.tn"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Rania Ben Slimane",
                            Name = "INSAT",
                            Rating = 4.7000000000000002,
                            Sections = "Informatique, Télécommunications, Automatique"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
